### ISSUE TITLE
Q: Spacing in and around interpolations?

### ISSUE THREAD

**Issue by kjhosein** [jonbrouse/terraform-style-guide#2]
Hello,

Have you given any thought to how you might format complex (or even simple) interpolations for ease of reading?

e.g.:

    "${floor(var.blah * pow(1024,4))}"

vs 

    "${ floor( var.blah * pow( 1024, 4 ) ) }"

Thanks!

**Comment by jonbrouse** [comment]
Taking a look at the interpolation documentation I would probably do the following:

```
"${floor(var.blah * pow(3, 2))}"
```

**Comment by kjhosein** [comment]
Thanks for the response Jon. 
Since I originally wrote this comment, I've written a fair amount of TF with moderately complex interpolations, and I've found the 2nd version (with the spaces) considerably easier to read/understand.

Of course, that's my own personal opinion. Either way, this is something you may want to include in your guide.
