### ISSUE TITLE
Default Resource Name?

### ISSUE THREAD

**Issue by JustinGrote** [jonbrouse/terraform-style-guide#4]
Since this seems to be the most "googleable" style guide I figured I'd ask here for incorporation.

For resource naming conventions, what should be standard? I've looked at a lot of the official terraform registry modules and best practices and it seems to be all over the place. Some examples I like:

1. The one in this style guide, same name as the resource without the provider. 
Example: `resource "aws_instance" "instance"`
2. Use "this" as a default reference, familiar to most object oriented programmers from classes
Example: `resource "aws_instance" "this"`
3. Use the name of the module. E.g. if the module is named MyCustomInstance
Example: `resource "aws_instance" "mycustominstance"`. I don't like this one because the module name can change, and its also part of the resource state reference already so its redundant.
4. Use the name of the .tf file it resides in, e.g. if the resource is defined in the module as main.tf then
Example: `resource "aws_instance" "main"`
5. Arbitrary names for each resource, treating them like variables
6. Similar to 2, but instead just "default" since "this" can be confusing to non-programmers. Any resource created beyond the first gets its own arbitrary name.

Then non default resources are either a prefix (instance2_<defaultname>), a suffix, or just a straight up replacement.

I've been playing with all these patterns in my modules, and the two I like best are 6 and 4. They keep things terse because I feel 1 just ends up being too redundant, especially if I am trying to terraform taint something it just ends up being a lot of unnecessary typing, since it's implicit and visible everywhere.

I would recommend 6, because 4 requires refactoring if you decide to move your code around in a module.

What's nice about 6 is everything has easy to reference names when looking at terraform state
aws_instance.default
aws_instance.custominstance

(Counted Instances)
aws_instance.default.0
aws_instance.default.1
aws_instance.myapp.0
aws_instance.myapp.1

(Module Items)
module.MyApp.aws_instance.default
module.MyApp.aws_instance.myapp.0

**Comment by jonbrouse** [comment]
Thank you for the post and I apologize for the delayed response. Simplicity and the reduction of cognitive overhead were the primary factors that went into writing this guide. The focus was to lower the barrier of entry for the entire organization to contribute and empower SWE's.

Setting a `default` creates an assumption and adds complexity. When considering outputs, one team or services's `default` could be `myapp`. When reading the output from a `terraform plan` of a module that has multiple resources of the same type, you can't discern what resource is `default` 

For example:

`resource "aws_sqs_queue" "publisher_sqs_queue"`
`resource "aws_sqs_queue" "consumer_sqs_queue"`
`resource "aws_sqs_queue" "notifications_sqs_queue"`

If someone new to a project ran `terraform plan` and saw a change to one of the queues, they could instantly know which queue the change related to.
