### ISSUE TITLE
Why forward slashes instead of hash mark for comments?

### ISSUE THREAD

**Issue by ntkach** [jonbrouse/terraform-style-guide#5]
I'm just curious if there's a special reason the doc shows two forward slashes (//) as opposed to a hash mark (#) for comments?  Does that make something or other easier/possible or is more just a style choice?  I'm not saying it's "wrong".  If it helps somehow I'd gladly adopt it.

**Comment by jonbrouse** [comment]
Updated the readme to reflect your suggestion.

**Comment by spliskamatyshak** [comment]
I would have written this as an option to use hash (#) or double-slash (//), but keep it consistent. Use one or the other; don't mix them.

**Comment by ntkach** [comment]
I agree 100% percent.  Consistency is key.

**Comment by jonbrouse** [comment]
Is this what you referring to? https://github.com/jonbrouse/terraform-style-guide/commit/4788493c538e7159132215dd572366ab1248ebf8
